package proxy

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.uber.org/zap/zaptest"

	"github.com/l17728/pairproxy/internal/config"
)

// ---------------------------------------------------------------------------
// extractSessionID 测试
// ---------------------------------------------------------------------------

func TestExtractSessionID_FromBody(t *testing.T) {
	body := []byte(`{"model":"claude-3-5-sonnet","session_id":"sess-abc123","messages":[]}`)
	req, _ := http.NewRequest(http.MethodPost, "/v1/messages", nil)
	sid := extractSessionID(req, body)
	assert.Equal(t, "sess-abc123", sid)
}

func TestExtractSessionID_FromHeader(t *testing.T) {
	req, _ := http.NewRequest(http.MethodPost, "/v1/messages", nil)
	req.Header.Set("X-Claude-Code-Session-Id", "header-session-xyz")
	sid := extractSessionID(req, nil)
	assert.Equal(t, "header-session-xyz", sid)
}

func TestExtractSessionID_AutoGenerated(t *testing.T) {
	req, _ := http.NewRequest(http.MethodPost, "/v1/messages", nil)
	sid := extractSessionID(req, nil)
	assert.True(t, strings.HasPrefix(sid, "auto-session-"), "expected auto-session- prefix, got: %s", sid)
}

func TestExtractSessionID_BodyTakesPriorityOverHeader(t *testing.T) {
	body := []byte(`{"session_id":"body-session"}`)
	req, _ := http.NewRequest(http.MethodPost, "/v1/messages", nil)
	req.Header.Set("X-Session-Id", "header-session")
	sid := extractSessionID(req, body)
	assert.Equal(t, "body-session", sid)
}

// ---------------------------------------------------------------------------
// expandCandidateModels 测试
// ---------------------------------------------------------------------------

func TestExpandCandidateModels_FiltersWildcards(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: []string{"claude-3-5-sonnet-20241022", "claude-3-*"}},
		{id: "t2", supportedModels: []string{"gpt-4o", "*"}},
		{id: "t3", supportedModels: []string{"DeepSeek-V3"}},
	}
	ids := []string{"t1", "t2", "t3"}
	models := expandCandidateModels(targets, ids)

	// 通配符 "claude-3-*" 和 "*" 应被过滤
	assert.Contains(t, models, "claude-3-5-sonnet-20241022")
	assert.Contains(t, models, "gpt-4o")
	assert.Contains(t, models, "DeepSeek-V3")
	for _, m := range models {
		assert.False(t, strings.Contains(m, "*"), "wildcard should be filtered: %s", m)
	}
}

func TestExpandCandidateModels_Deduplicated(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: []string{"gpt-4o", "gpt-4-turbo"}},
		{id: "t2", supportedModels: []string{"gpt-4o", "gpt-3.5-turbo"}},
	}
	models := expandCandidateModels(targets, []string{"t1", "t2"})

	count := 0
	for _, m := range models {
		if m == "gpt-4o" {
			count++
		}
	}
	assert.Equal(t, 1, count, "gpt-4o should appear only once after deduplication")
}

func TestExpandCandidateModels_OnlyIncludesRequestedIDs(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: []string{"model-A"}},
		{id: "t2", supportedModels: []string{"model-B"}},
		{id: "t3", supportedModels: []string{"model-C"}},
	}
	models := expandCandidateModels(targets, []string{"t1", "t3"}) // t2 excluded
	assert.Contains(t, models, "model-A")
	assert.Contains(t, models, "model-C")
	assert.NotContains(t, models, "model-B")
}

func TestExpandCandidateModels_EmptySupportedModels_Skipped(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: nil}, // no restriction
		{id: "t2", supportedModels: []string{"gpt-4o"}},
	}
	models := expandCandidateModels(targets, []string{"t1", "t2"})
	// t1 has no supported models, it's skipped (can't contribute to candidate list)
	assert.Equal(t, []string{"gpt-4o"}, models)
}

// ---------------------------------------------------------------------------
// groupProviderFromTargets 测试
// ---------------------------------------------------------------------------

func TestGroupProviderFromTargets_ReturnsFirstMatchingProvider(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: []string{"DeepSeek-V3"}, provider: "openai"},
		{id: "t2", supportedModels: []string{"gpt-4o"}, provider: "openai"},
		{id: "t3", supportedModels: []string{"claude-3-5-sonnet"}, provider: "anthropic"},
	}
	got := groupProviderFromTargets(targets, []string{"t1", "t2"})
	assert.Equal(t, "openai", got)
}

func TestGroupProviderFromTargets_OnlySearchesRequestedIDs(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", provider: "anthropic"},
		{id: "t2", provider: "openai"},
	}
	// t1 不在 groupTargetIDs 中，应跳过
	got := groupProviderFromTargets(targets, []string{"t2"})
	assert.Equal(t, "openai", got)
}

func TestGroupProviderFromTargets_EmptyProvider_Skipped(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", provider: ""},
		{id: "t2", provider: "openai"},
	}
	got := groupProviderFromTargets(targets, []string{"t1", "t2"})
	assert.Equal(t, "openai", got, "should skip empty provider and return first non-empty")
}

func TestGroupProviderFromTargets_NoMatch_ReturnsEmpty(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", provider: "openai"},
	}
	got := groupProviderFromTargets(targets, []string{"t99"}) // t99 不存在
	assert.Equal(t, "", got)
}

func TestGroupProviderFromTargets_EmptyInputs(t *testing.T) {
	assert.Equal(t, "", groupProviderFromTargets(nil, nil))
	assert.Equal(t, "", groupProviderFromTargets([]lbTarget{}, []string{}))
}

// ---------------------------------------------------------------------------
// resolveModelToTarget 测试
// ---------------------------------------------------------------------------

func TestResolveModelToTarget_ExactMatch(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: []string{"claude-3-5-sonnet-20241022"}},
		{id: "t2", supportedModels: []string{"gpt-4o"}},
	}
	result := resolveModelToTarget("gpt-4o", targets, []string{"t1", "t2"})
	assert.Equal(t, "t2", result)
}

func TestResolveModelToTarget_WildcardMatch(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: []string{"claude-3-5-*"}},
		{id: "t2", supportedModels: []string{"gpt-4o"}},
	}
	result := resolveModelToTarget("claude-3-5-sonnet-20241022", targets, []string{"t1", "t2"})
	assert.Equal(t, "t1", result)
}

func TestResolveModelToTarget_NoMatch_FallbackToFirst(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: []string{"model-A"}},
		{id: "t2", supportedModels: []string{"model-B"}},
	}
	result := resolveModelToTarget("model-unknown", targets, []string{"t1", "t2"})
	assert.Equal(t, "t1", result, "should fall back to first target when no match")
}

func TestResolveModelToTarget_NoSupportedModels_MatchesAll(t *testing.T) {
	targets := []lbTarget{
		{id: "t1", supportedModels: []string{"model-A"}},
		{id: "t2", supportedModels: nil}, // no restriction → matches all
	}
	result := resolveModelToTarget("anything", targets, []string{"t1", "t2"})
	// t1 doesn't match, t2 has no restriction → t2
	assert.Equal(t, "t2", result)
}

// ---------------------------------------------------------------------------
// ModelRouterClient.Route 测试（使用 httptest.Server）
// ---------------------------------------------------------------------------

func newTestRouterServer(t *testing.T, handler http.HandlerFunc) (*httptest.Server, *ModelRouterClient) {
	t.Helper()
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)
	logger := zaptest.NewLogger(t)
	client := NewModelRouterClient(config.ModelRouterConfig{
		URL:     srv.URL,
		Timeout: 2 * time.Second,
	}, logger)
	return srv, client
}

func TestModelRouterClient_Route_Success(t *testing.T) {
	_, client := newTestRouterServer(t, func(w http.ResponseWriter, r *http.Request) {
		// Verify required headers
		assert.Equal(t, "req-123", r.Header.Get("X-Span-Id"))
		assert.Equal(t, "alice", r.Header.Get("X-Domain-Id"))
		assert.Equal(t, "alice", r.Header.Get("X-User-Alias"))

		// Verify request body contains session_id and candidate_models
		var body map[string]interface{}
		require.NoError(t, json.NewDecoder(r.Body).Decode(&body))
		assert.Equal(t, "sess-001", body["session_id"])
		assert.Equal(t, "claude-3-5-sonnet-20241022", body["model"])

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{ //nolint:errcheck
			"model_rankings": []map[string]interface{}{
				{"rank": 2, "model": "gpt-4o", "score": 0.7},
				{"rank": 1, "model": "DeepSeek-V3", "score": 0.9},
			},
		})
	})

	body := []byte(`{"model":"claude-3-5-sonnet-20241022","messages":[{"role":"user","content":"hello"}]}`)
	selected, _, err := client.Route(context.Background(), "req-123", "alice", "sess-001", body, "claude-3-5-sonnet-20241022", []string{"DeepSeek-V3", "gpt-4o"}, nil)
	require.NoError(t, err)
	assert.Equal(t, "DeepSeek-V3", selected, "should select rank=1 model")
}

func TestModelRouterClient_Route_ServerError(t *testing.T) {
	_, client := newTestRouterServer(t, func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	})
	_, _, err := client.Route(context.Background(), "req-x", "user", "sess", nil, "", nil, nil)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "non-200")
}

func TestModelRouterClient_Route_EmptyRankings(t *testing.T) {
	_, client := newTestRouterServer(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{ //nolint:errcheck
			"model_rankings": []interface{}{},
		})
	})
	_, _, err := client.Route(context.Background(), "req-y", "user", "sess", nil, "", nil, nil)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "empty model_rankings")
}

func TestModelRouterClient_Route_InvalidJSON(t *testing.T) {
	_, client := newTestRouterServer(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`not json`)) //nolint:errcheck
	})
	_, _, err := client.Route(context.Background(), "req-z", "user", "sess", nil, "", nil, nil)
	assert.Error(t, err)
}

func TestModelRouterClient_Route_Timeout(t *testing.T) {
	logger := zaptest.NewLogger(t)
	// Create a slow server
	slow := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(200 * time.Millisecond)
		w.WriteHeader(http.StatusOK)
	}))
	defer slow.Close()

	// Client with 50ms timeout
	client := NewModelRouterClient(config.ModelRouterConfig{
		URL:     slow.URL,
		Timeout: 50 * time.Millisecond,
	}, logger)

	_, _, err := client.Route(context.Background(), "req-t", "user", "sess", nil, "", nil, nil)
	assert.Error(t, err, "should time out")
}

func TestModelRouterClient_Route_NoURL(t *testing.T) {
	logger := zaptest.NewLogger(t)
	client := NewModelRouterClient(config.ModelRouterConfig{URL: ""}, logger)
	_, _, err := client.Route(context.Background(), "", "", "", nil, "", nil, nil)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "not configured")
}

func TestModelRouterClient_Route_PreservesOriginalModel(t *testing.T) {
	var capturedBody map[string]interface{}
	srv, client := newTestRouterServer(t, func(w http.ResponseWriter, r *http.Request) {
		json.NewDecoder(r.Body).Decode(&capturedBody) //nolint:errcheck
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{ //nolint:errcheck
			"model_rankings": []map[string]interface{}{{"rank": 1, "model": "gpt-4o", "score": 1.0}},
		})
	})
	_ = srv

	body := []byte(`{"model":"claude-3-5-sonnet-20241022","messages":[]}`)
	client.Route(context.Background(), "r1", "u1", "s1", body, "claude-3-5-sonnet-20241022", nil, nil) //nolint:errcheck

	// Model should NOT be changed to "auto" — original model preserved
	assert.Equal(t, "claude-3-5-sonnet-20241022", capturedBody["model"],
		"original model should be preserved, not changed to 'auto'")
}
